version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nexus-gaming-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nexus_gaming
      MYSQL_USER: nexus_user
      MYSQL_PASSWORD: nexus_password
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - nexus-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: nexus-gaming-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nexus-network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nexus-gaming-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: nexus_user
      PMA_PASSWORD: nexus_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - nexus-network

volumes:
  mysql_data:
  redis_data:

networks:
  nexus-network:
    driver: bridge 