# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # 根據 memory-bank/techContext.md

    - name: Install dependencies # 假設 Python 項目在 ai-service/ 目錄下，且使用 requirements.txt
      run: |
        python -m pip install --upgrade pip
        if [ -f ai-service/requirements.txt ]; then pip install -r ai-service/requirements.txt; fi
      working-directory: .

    - name: Lint with flake8 # 假設使用 flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 ai-service --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ai-service --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: .

    - name: Test with pytest # 假設使用 pytest
      run: |
        pip install pytest
        pytest ai-service
      working-directory: . 